version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8765:8765"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8765
    restart: unless-stopped